// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgk9_XqoCKNzFyedaN7SFRzc2qyx7bPfo',
    appId: '1:37959648879:web:58c6cd94eb3dfbd3672f9a',
    messagingSenderId: '37959648879',
    projectId: 'assignment-8c0e9',
    authDomain: 'assignment-8c0e9.firebaseapp.com',
    storageBucket: 'assignment-8c0e9.appspot.com',
    measurementId: 'G-H4RHTDSH13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz_sLOMHJpT5O5-l5oL8P5kDgubs89TdE',
    appId: '1:37959648879:android:bc3af609b3bf44e2672f9a',
    messagingSenderId: '37959648879',
    projectId: 'assignment-8c0e9',
    storageBucket: 'assignment-8c0e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXwhxY_w374Y7ig5zcWxrqlPkcntrf7Os',
    appId: '1:37959648879:ios:0f20d15da762ae56672f9a',
    messagingSenderId: '37959648879',
    projectId: 'assignment-8c0e9',
    storageBucket: 'assignment-8c0e9.appspot.com',
    iosClientId: '37959648879-5i1u7k3cp801t5964rdmh7mvu0u1k0l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXwhxY_w374Y7ig5zcWxrqlPkcntrf7Os',
    appId: '1:37959648879:ios:0f20d15da762ae56672f9a',
    messagingSenderId: '37959648879',
    projectId: 'assignment-8c0e9',
    storageBucket: 'assignment-8c0e9.appspot.com',
    iosClientId: '37959648879-5i1u7k3cp801t5964rdmh7mvu0u1k0l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );
}
